/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lc_SystemUtils */

#ifndef _Included_com_example_lc_SystemUtils
#define _Included_com_example_lc_SystemUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lc_SystemUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lc_SystemUtils_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lc_SystemUtils
 * Method:    getProperity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lc_SystemUtils_getProperity
  (JNIEnv *, jclass, jstring, jstring);
/*
 * Class:     com_example_lc_SystemUtils
 * Method:    getProperity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_example_lc_SystemUtils_setProperity
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
