/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <dlfcn.h>
#include <string.h>
#include <sys/system_properties.h>
#include "properties.h"
#include "com_example_lc_SystemUtils.h"


/*
 * Class:     com_example_lc_SystemUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lc_SystemUtils_getString
        (JNIEnv *env, jobject jclass){
    char *str="Hello Fron Jni code";
    return(*env)->NewStringUTF(env,str);
}


/*
 * Class:     com_example_lc_SystemUtils
 * Method:    getProperity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lc_SystemUtils_getProperity
        (JNIEnv *env, jobject jclass, jstring jkey, jstring jdefVal){
    const char *key= (*env)->GetStringUTFChars(env,jkey,NULL);
    const char *defVal=(*env)->GetStringUTFChars(env,jdefVal,NULL);
    char buff[100] ={'\0',};
    property_get(key,buff,defVal);
    return (*env)->NewStringUTF(env,buff);
}
/*
 * Class:     com_example_lc_SystemUtils
 * Method:    setProperity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_example_lc_SystemUtils_setProperity
        (JNIEnv *env, jobject jclass, jstring jkey, jstring jdefVal){
    const char *key= (*env)->GetStringUTFChars(env,jkey,NULL);
    const char *defVal=(*env)->GetStringUTFChars(env,jdefVal,NULL);
    property_set(key,defVal);
}


int property_get(const char *key,char *value, const char *default_value){
    int len;
    len = __system_property_get(key,value);
    if(len > 0){
        return len;
    }
    if(default_value){
        len = strlen(default_value);
        if(len >= PROPERTY_VALUE_MAX){
            len = PROPERTY_VALUE_MAX - 1;
        }
        memcpy(value,default_value,len);
        value[len] = '\0';
    }
    return len;
}

int property_set(const char *key, const char *value){
    return __system_property_set(key,value);
}

#if (__ANDROID_API__ >= 21)
// Android 'L' makes __system_property_get a non-global symbol.
// Here we provide a stub which loads the symbol from libc via dlsym.
typedef int (*PFN_SYSTEM_PROP_GET)(const char *, char *);
int __system_property_get(const char* name, char* value)
{
    static PFN_SYSTEM_PROP_GET __real_system_property_get = NULL;
    if (!__real_system_property_get) {
        // libc.so should already be open, get a handle to it.
        void *handle = dlopen("libc.so", RTLD_NOLOAD);
        if (!handle) {
            __android_log_print(ANDROID_LOG_ERROR, "foobar", "Cannot dlopen libc.so: %s.\n", dlerror());
        } else {
            __real_system_property_get = (PFN_SYSTEM_PROP_GET)dlsym(handle, "__system_property_get");
        }
        if (!__real_system_property_get) {
            __android_log_print(ANDROID_LOG_ERROR, "foobar", "Cannot resolve __system_property_get(): %s.\n", dlerror());
        }
    }
    return (*__real_system_property_get)(name, value);
}

typedef int (*PFN_SYSTEM_PROP_SET)(const char *, char *);
int __system_property_set(const char* name, char* value)
{
    static PFN_SYSTEM_PROP_SET __real_system_property_set = NULL;
    if (!__real_system_property_set) {
        // libc.so should already be open, get a handle to it.
        void *handle = dlopen("libc.so", RTLD_NOLOAD);
        if (!handle) {
            __android_log_print(ANDROID_LOG_ERROR, "foobar", "Cannot dlopen libc.so: %s.\n", dlerror());
        } else {
            __real_system_property_set = (PFN_SYSTEM_PROP_SET)dlsym(handle, "__system_property_set");
        }
        if (!__real_system_property_set) {
            __android_log_print(ANDROID_LOG_ERROR, "foobar", "Cannot resolve __system_property_set(): %s.\n", dlerror());
        }
    }
    return (*__real_system_property_set)(name, value);
}
#endif // __ANDROID_API__ >= 21